#!/bin/bash
# Megaupload Premium Downloader for Linux 0.2
# Mohsin Mirza <named.conf@gmail.com>
# ex: megaupload-dl filename
# ex: cat filename | megaupload-dl

FILE=""
if [ "$1" == "" ]; then
   FILE="/dev/stdin"
else
   FILE="$1"
   if [ ! -f $FILE ]; then
        echo "$FILE : does not exists"
        exit 1
   elif [ ! -r $FILE ]; then
        echo "$FILE: can not read"
        exit 2
   fi
fi
# Variables

USERNAME=YOUR_USERNAME
PASS=YOUR_PASSWORD
COOKIEJAR=$HOME/.cookies
if [ ! -d $COOKIEJAR ]; then
        mkdir $COOKIEJAR
fi

## Do not change anything below here ##

wget --save-cookies $COOKIEJAR/.megaupload --post-data "login=1&redir=1&username=$USERNAME&password=$PASS" -O - http://www.megaupload.com/index.php?c=login > /dev/null
exec 3<&0
exec 0<$FILE
while read lines
do
links=$lines
filenames=`curl -s $lines  | grep "File name" | perl -wlne'm/span>(.*)<\/span/i && print $1' | cut -d ">" -f2`
echo $filenames; curl -L --cookie $COOKIEJAR/.megaupload $links -# -C - -o "$filenames"
done
exec 0<&3
